version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        volumes:
            - .:/var/www/html
        depends_on:
            - db
        environment:
            DB_HOST: db
            DB_PORT: 5432
            DB_DATABASE: eventos
            DB_USERNAME: postgres
            DB_PASSWORD: admin
        networks:
            - app-network

    db:
        image: postgres:13
        environment:
            POSTGRES_DB: eventos
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: admin
        ports:
            - "5432:5432"
        volumes:
            - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
