version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        volumes:
            - .:/var/www/html
        depends_on:
            - db
        environment:
            DB_HOST: demo5.linkisite.com
            DB_PORT: 3306
            DB_DATABASE: demo5linkisite_mydb2
            DB_USERNAME: demo5linkisite_myuser2
            DB_PASSWORD: uB7UsE_3Bzzh
        networks:
            - app-network

    db:
        image: mysql:latest
        environment:
            MYSQL_DATABASE: demo5linkisite_mydb2
            MYSQL_USER: demo5linkisite_myuser2
            MYSQL_PASSWORD: uB7UsE_3Bzzh
            MYSQL_ROOT_PASSWORD: root_password_here
        ports:
            - "3306:3306"
        volumes:
            - ./mysql-data:/var/lib/mysql
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
